spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.20.2.105:3306/test_blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: rWd3Hb+AzNg3IXF1b5vD+g==
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: info
    com.lrm: debug
  file: log/blog-dev.log



